name: AUTO PR Review
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  auto-bot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.9

      - name: Install gh CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate gh CLI
        run: |
          echo "${{ secrets.BOT_GH_TOKEN }}" | gh auth login --with-token

      - name: Clone a private repository
        run: |
          git clone https://x-access-token:${{ secrets.BOT_GH_TOKEN }}@github.com/SSS-Core-AI/poc-pull-request-bot.git
          cd poc-pull-request-bot

      - name: Create .env file with multiple variables
        run: |
          echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" > .env
          echo "LANGFUSE_SECRET_KEY=${{secrets.LANGFUSE_SECRET_KEY}}" >> .env
          echo "LANGFUSE_PUBLIC_KEY=${{secrets.LANGFUSE_PUBLIC_KEY}}" >> .env
          echo "LANGFUSE_HOST=${{secrets.LANGFUSE_HOST}}" >> .env
          echo "BOT_GH_PAT=${{secrets.BOT_GH_PAT}}" >> .env
          echo "BOT_GH_TOKEN=${{secrets.BOT_GH_TOKEN}}" >> .env

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Download PR Patch
        run: |
            curl -L \
            -H "Authorization: Bearer ${{secrets.BOT_GH_TOKEN}}" \
            -H "Accept: application/vnd.github.patch" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.event.pull_request.url }}" -o pr.patch

      - name: Debug
        run: |
          echo '${{ toJSON(github.event) }}' | jq .
          cat pr.patch

      - name: Execute
        run: |
          python main.py pr.patch '${{ github.event.pull_request.comments_url}}'